apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-routing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sts-home
                port:
                  number: 8090

