version: '3.9'
name: react-springboot-app
services:
  frontend:
    image: react-app:1
    build:
      context: ./docker-react-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: springboot-app:1
    build:
      context: ./docker-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/mydb
      DB_USER: postgres
      DB_PWD: postgres
    depends_on:
      - db
  
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb

